export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const ACTIVATION_SUCCESS = "ACTIVATION_SUCCESS";
export const ACTIVATION_FAIL = "ACTIVATION_FAIL";
export const USER_LOADED_SUCCESS = "USER_LOADED_SUCCESS";
export const USER_LOADED_FAIL = "USER_LOADED_FAIL";
export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL";
export const PASSWORD_RESET_FAIL = "PASSWORD_RESET_FAIL";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_CONFIRM_FAIL = "PASSWORD_RESET_CONFIRM_FAIL";
export const PASSWORD_RESET_CONFIRM_SUCCESS = "PASSWORD_RESET_CONFIRM_SUCCESS";
export const LOGOUT = "LOGOUT";

export const GETPOSTS_SUCCESS = "GETPOSTS_SUCCESS";
export const GETPOSTS_FAIL = "GETPOSTS_FAIL";

export const GETPOST_SUCCESS = "GETPOST_SUCCESS";
export const GETPOST_FAIL = "GETPOST_FAIL";

export const GETUSERPOSTS_SUCCESS = "GETUSERPOSTS_SUCCESS";
export const GETUSERPOSTS_FAIL = "GETUSERPOSTS_FAIL";

export const SETPROFILEIMAGE_SUCCESS = "SETPROFILEIMAGE_SUCCESS";
export const GETPROFILEIMAGE_SUCCESS = "GETPROFILEIMAGE_SUCCESS";

export const GETALLPOSTS_SUCCESS = "GETALLPOSTS_SUCCESS";
