# Generated by Django 3.2.9 on 2021-12-25 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_post_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='username',
        ),
    ]
