# Generated by Django 3.2.9 on 2021-12-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_like_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='follower',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='following',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
