# Generated by Django 3.2.9 on 2022-04-05 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_profileimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created', '-updated', '-no_of_likes']},
        ),
    ]
