# Generated by Django 3.2.9 on 2022-04-15 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_alter_post_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.TextField()),
                ('website', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('no_of_followers', models.IntegerField(blank=True, default=0, null=True)),
                ('no_of_following', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
