# Generated by Django 3.2.9 on 2022-03-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='profile_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
