# Generated by Django 3.2.9 on 2022-04-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_useraccount_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='no_of_followers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='no_of_following',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
