# Generated by Django 3.2.9 on 2022-04-15 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220415_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='no_of_followers',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='no_of_following',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='website',
        ),
    ]
